version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dre
    ports: ["5434:5432"]
    volumes:
      - /home/dev/docker-data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: ./apps/api
    env_file: ./apps/api/.env
    depends_on: [db]
    ports: ["4000:4000"]  
  web:
    build: ./apps/web
    env_file: ./apps/web/.env
    depends_on: [api]
    ports: ["3000:3000"]